# Use Travis to test on Mac and Linux
language: node_js
os:
  - linux
  - osx
node_js:
  - 'node'
  - 'lts/*'
cache:
  directories:
    - 'node_modules'
install:
  - '[ -f package-lock.json ] && [ npm ci --help ] && npm ci || npm install'
