# Use Appveyor to test on Windows
environment:
  matrix:
    - nodejs_version: ''
    - nodejs_version: 'LTS'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
#   - npm run build
  - npm test

# Don't actually build.
build: off

cache:
  - node_modules
